version: "3.9"
services:
  jenkins-server:
    image: jenkins/jenkins:lts-alpine
    container_name: jenkins
    user: $UID:$GID
    restart: always
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - $JENKINS_HOME:/var/jenkins_home
      - $JENKINS_DOCKER_CERTS:/certs/client:ro
    ports:
      - "41001:8080"
      - "50000:50000"
    networks:
      - jenkins
  jenkins-worker:
    image: alpine/socat
    container_name: jenkins_worker
    restart: always
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 127.0.0.1:2376:2375
      - 3000:8080
    networks:
      - jenkins
    user: root
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"
networks:
  jenkins:
    name: jenkins